Feature/fga/timeline thread decoration
vector-im/element-x-android pull request #1298
Opened 2023-09-13 10:13 UTC by ganfra

Closes https://github.com/vector-im/element-x-android/issues/1236

2023-09-13 16:30 UTC, callumu commented
Yes this looks good 👍

2023-09-14 06:05 UTC, jmartinesp requested changes
There is a regression in one of the screenshots.

2023-09-14 06:05 UTC, jmartinesp commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_null_TimelineItemEventRowWithReplyLight_0_null,NEXUS_5,1.0,en].png
The last reply here broke, it must be missing the top padding.

2023-09-14 06:05 UTC, jmartinesp commented on tests/uitests/src/test/snapshots/images/ui_S_t[l.textcomposer_null_TextComposerReply-D-3_4_null,NEXUS_5,1.0,en].png
I just realised the different font sizes and colors in the composer. Maybe not something to fix in this PR, but we should take a look at it later.

2023-09-14 06:30 UTC, ganfra commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_null_TimelineItemEventRowWithReplyLight_0_null,NEXUS_5,1.0,en].png
Thats weird because its not broken in real or in the preview 🤔

2023-09-14 06:49 UTC, jmartinesp commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_null_TimelineItemEventRowWithReplyLight_0_null,NEXUS_5,1.0,en].png
Maybe it's just an issue with paparazzi then. My previews look good as well, but this screenshot is broken when generated locally.

2023-09-14 06:51 UTC, jmartinesp approved these changes
LGTM, the broken screenshot isn't great, but the actual code seems to work fine.

2023-09-14 15:01 UTC, bmarty commented on tests/uitests/src/test/snapshots/images/ui_S_t[l.textcomposer_null_TextComposerReply-D-3_4_null,NEXUS_5,1.0,en].png
Isn't just the placeholder which changed from "Message" to "Message..."?

2023-09-14 16:45 UTC, merged